Conflux-Chain/conflux-protocol

components.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/5)
=> Remove todo solved in #2

incentive.tex, symbols.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/6)
=> CIP 10-finalize mining reward

components.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/9)
=> Refine transaction action field

tx_processing.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/11)
=> Refactor section in transaction introduction

tx_processing.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/12)
=> Remove duplicate lines incurred in #11

tx_processing.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/13)
=> Add an exceptional case in tx processing

contract_creation.tex, tx_processing.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/14)
=> Fix missing parameter in contract creation

contract_creation.tex, destruction.tex, message_call.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/15)
=> Fix typo in symbols

chain_execution.tex, collateral.tex, contract_creation.tex, destruction.tex, execution_model.tex, instructions.tex, tx_processing.tex
This PR includes [CIP8](https://github.com/Conflux-Chain/CIPs/blob/master/CIPs/cip-8.md), [CIP12](https://github.com/Conflux-Chain/CIPs/blob/master/CIPs/cip-12.md) and [CIP16](https://github.com/Conflux-Chain/CIPs/blob/master/CIPs/cip-16.md)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/16)
=> Update logic for collateral and suicide

internal_contract.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/19)
=> Fix where storing staking info

contract_creation.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/20)
=> The default admin is original sender, not sender

components.tex, tx_processing.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/21)
=> Fix dirty flag description

tech-specification.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/22)
=> Fix case sensitive

instructions.tex, internal_contract.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/24)
=> Fix some issues

mp_eval_hash.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/26)
=> Refine PoW Computation

chain_execution.tex, components.tex, internal_contract_spec.tex, mp_eval_hash.tex, pow.tex, tech-specification.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/27)
=> Fix PoW & Upgrade to Octopus

incentive.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/29)
=> Fix a bug in adaptive block

version.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/30)
=> Fix version script

execution_model.tex, instructions.tex, tx_processing.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/31)
=> Revise reentrancy protection rule

chain_execution.tex, symbols.tex, tech-specification.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/32)
=> Correct init difficulty & add deprecated info

incentive.tex, symbols.tex, tech-specification.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/34)
=> Upgrade to Tanzanite

execution_model.tex
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-chain/conflux-protocol/33)
=> Change SELFDESTRUCT to SUICIDE and make some small improvements
